# Generated by Django 3.1.4 on 2021-03-15 15:29

import Common.utils.uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AccountManagement', '0001_initial'),
        ('ContentManagement', '0002_auto_20210315_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountContent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    models.UUIDField(
                        default=Common.utils.uuid.pkgen,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('status', models.IntegerField(default=1)),
                (
                    'account',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='questions',
                        to='AccountManagement.account',
                    ),
                ),
                (
                    'question',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='account',
                        to='ContentManagement.question',
                    ),
                ),
            ],
            options={
                'db_table': 'account_content',
            },
        ),
    ]
