# Generated by Django 3.1.4 on 2021-03-15 13:57

import Common.utils.uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    models.UUIDField(
                        default=Common.utils.uuid.pkgen,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('content', models.CharField(max_length=200)),
                ('status', models.IntegerField(default=1)),
                (
                    'type',
                    models.IntegerField(
                        choices=[(1, 'Admin'), (2, 'User'), (3, 'Typing')], default=2
                    ),
                ),
            ],
            options={
                'db_table': 'question',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    models.UUIDField(
                        default=Common.utils.uuid.pkgen,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('content', models.CharField(max_length=200)),
                ('status', models.IntegerField(default=1)),
                (
                    'question',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='answers',
                        to='ContentManagement.question',
                    ),
                ),
            ],
            options={
                'db_table': 'answer',
            },
        ),
    ]
