# Generated by Django 3.1.4 on 2021-03-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContentManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.IntegerField(
                choices=[(1, 'Multichoice'), (2, 'Selec'), (3, 'Typing')], default=2
            ),
        ),
    ]
