# Generated by Django 3.1.4 on 2021-03-16 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContentManagement', '0002_auto_20210315_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
