# Generated by Django 3.1.4 on 2021-03-16 00:28

import Common.utils.uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ContentManagement', '0003_question_tag'),
        ('AccountManagement', '0001_initial'),
        ('AccountContentManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='accountquestion',
            table='account_question',
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    models.UUIDField(
                        default=Common.utils.uuid.pkgen,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('status', models.IntegerField(default=1)),
                (
                    'account',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='answers',
                        to='AccountManagement.account',
                    ),
                ),
                (
                    'answer',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='account',
                        to='ContentManagement.answer',
                    ),
                ),
            ],
            options={
                'db_table': 'user_answer',
            },
        ),
    ]
