# Generated by Django 3.1.4 on 2021-03-16 00:37

import Common.utils.uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ContentManagement', '0003_question_tag'),
        ('AccountManagement', '0001_initial'),
        ('AccountContentManagement', '0002_auto_20210316_0028'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuestionVote',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    models.UUIDField(
                        default=Common.utils.uuid.pkgen,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'value',
                    models.IntegerField(
                        choices=[(1, 'UPVOTE'), (-1, 'DOWNVOTE')], default=1
                    ),
                ),
                (
                    'account',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='question_votes',
                        to='AccountManagement.account',
                    ),
                ),
                (
                    'answer',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='votes',
                        to='ContentManagement.question',
                    ),
                ),
            ],
            options={
                'db_table': 'user_question_vote',
            },
        ),
        migrations.CreateModel(
            name='UserAnswerVote',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    models.UUIDField(
                        default=Common.utils.uuid.pkgen,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'value',
                    models.IntegerField(
                        choices=[(1, 'UPVOTE'), (-1, 'DOWNVOTE')], default=1
                    ),
                ),
                (
                    'account',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='answer_votes',
                        to='AccountManagement.account',
                    ),
                ),
                (
                    'answer',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='votes',
                        to='ContentManagement.answer',
                    ),
                ),
            ],
            options={
                'db_table': 'user_answer_vote',
            },
        ),
    ]
