# Generated by Django 3.1.4 on 2021-03-16 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AccountContentManagement', '0003_useranswervote_userquestionvote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userquestionvote',
            old_name='answer',
            new_name='question',
        ),
    ]
