# Generated by Django 3.1.4 on 2021-03-15 13:57

import Common.utils.uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    models.UUIDField(
                        default=Common.utils.uuid.pkgen,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                (
                    'username',
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                (
                    'email',
                    models.EmailField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ('dob', models.DateField(blank=True, null=True)),
                (
                    'phone_number',
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ('avatar', models.URLField(blank=True, max_length=150, null=True)),
                (
                    'type',
                    models.IntegerField(choices=[(0, 'Admin'), (1, 'User')], default=1),
                ),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'account',
            },
        ),
    ]
